version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
      - "5555:5555"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.backend
