
services:
  db:
    image: postgres:15
    container_name: myapp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_db
    restart: always
    ports:
      - "5433:5432" # ホスト5433→コンテナ5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

