# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class Baseusers(_PrismaModel):
    __prisma_model__: ClassVar[Literal['users']] = 'users'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.usersActions[_PrismaModelT]':
        from .client import get_client

        return actions.usersActions[_PrismaModelT](client or get_client(), cls)


class Basecare_settings(_PrismaModel):
    __prisma_model__: ClassVar[Literal['care_settings']] = 'care_settings'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.care_settingsActions[_PrismaModelT]':
        from .client import get_client

        return actions.care_settingsActions[_PrismaModelT](client or get_client(), cls)


class Basecare_logs(_PrismaModel):
    __prisma_model__: ClassVar[Literal['care_logs']] = 'care_logs'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.care_logsActions[_PrismaModelT]':
        from .client import get_client

        return actions.care_logsActions[_PrismaModelT](client or get_client(), cls)


class Basereflection_notes(_PrismaModel):
    __prisma_model__: ClassVar[Literal['reflection_notes']] = 'reflection_notes'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.reflection_notesActions[_PrismaModelT]':
        from .client import get_client

        return actions.reflection_notesActions[_PrismaModelT](client or get_client(), cls)


class Basemessage_logs(_PrismaModel):
    __prisma_model__: ClassVar[Literal['message_logs']] = 'message_logs'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.message_logsActions[_PrismaModelT]':
        from .client import get_client

        return actions.message_logsActions[_PrismaModelT](client or get_client(), cls)


class Basewalk_missions(_PrismaModel):
    __prisma_model__: ClassVar[Literal['walk_missions']] = 'walk_missions'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.walk_missionsActions[_PrismaModelT]':
        from .client import get_client

        return actions.walk_missionsActions[_PrismaModelT](client or get_client(), cls)


class Basepayment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['payment']] = 'payment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.paymentActions[_PrismaModelT]':
        from .client import get_client

        return actions.paymentActions[_PrismaModelT](client or get_client(), cls)


class Basewebhook_events(_PrismaModel):
    __prisma_model__: ClassVar[Literal['webhook_events']] = 'webhook_events'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.webhook_eventsActions[_PrismaModelT]':
        from .client import get_client

        return actions.webhook_eventsActions[_PrismaModelT](client or get_client(), cls)


