# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template client.py.jinja --
import warnings
import logging
from datetime import timedelta
from pathlib import Path
from types import TracebackType
from typing_extensions import override

from pydantic import BaseModel

from . import types, models, errors, actions
from ._base_client import BasePrisma, UseClientDefault, USE_CLIENT_DEFAULT
from .types import DatasourceOverride, HttpConfig, MetricsFormat
from ._types import BaseModelT, PrismaMethod, TransactionId, Datasource
from .bases import _PrismaModel
from ._builder import QueryBuilder, dumps
from .generator.models import EngineType, OptionalValueFromEnvVar, BinaryPaths
from ._compat import removeprefix, model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_TX_MAX_WAIT, DEFAULT_TX_TIMEOUT
from ._raw_query import deserialize_raw_results
from ._metrics import Metrics
from .metadata import PRISMA_MODELS, RELATIONAL_FIELD_MAPPINGS
from ._transactions import AsyncTransactionManager, SyncTransactionManager

# re-exports
from ._base_client import SyncBasePrisma, AsyncBasePrisma, load_env as load_env
from ._registry import (
    register as register,
    get_client as get_client,
    RegisteredClient as RegisteredClient,
)


__all__ = (
    'ENGINE_TYPE',
    'SCHEMA_PATH',
    'BINARY_PATHS',
    'Batch',
    'Prisma',
    'Client',
    'load_env',
    'register',
    'get_client',
)

log: logging.Logger = logging.getLogger(__name__)

SCHEMA_PATH = Path('C:/Dev/Section9_TeamC/backend/prisma/schema.prisma')
PACKAGED_SCHEMA_PATH = Path(__file__).parent.joinpath('schema.prisma')
ENGINE_TYPE: EngineType = EngineType.binary
BINARY_PATHS = model_parse(BinaryPaths, {'queryEngine': {'windows': 'C:\\Users\\yamaz\\.cache\\prisma-python\\binaries\\5.17.0\\393aa359c9ad4a4bb28630fb5613f9c281cde053\\node_modules\\prisma\\query-engine-windows.exe'}, 'introspectionEngine': {}, 'migrationEngine': {}, 'libqueryEngine': {}, 'prismaFmt': {}})


class Prisma(AsyncBasePrisma):
    # Note: these property names can be customised using `/// @Python(instance_name: '...')`
    # https://prisma-client-py.readthedocs.io/en/stable/reference/schema-extensions/#instance_name
    users: 'actions.usersActions[models.users]'
    care_settings: 'actions.care_settingsActions[models.care_settings]'
    care_logs: 'actions.care_logsActions[models.care_logs]'
    reflection_notes: 'actions.reflection_notesActions[models.reflection_notes]'
    message_logs: 'actions.message_logsActions[models.message_logs]'
    walk_missions: 'actions.walk_missionsActions[models.walk_missions]'
    payment: 'actions.paymentActions[models.payment]'
    webhook_events: 'actions.webhook_eventsActions[models.webhook_events]'

    __slots__ = (
        'users',
        'care_settings',
        'care_logs',
        'reflection_notes',
        'message_logs',
        'walk_missions',
        'payment',
        'webhook_events',
    )

    def __init__(
        self,
        *,
        use_dotenv: bool = True,
        log_queries: bool = False,
        auto_register: bool = False,
        datasource: DatasourceOverride | None = None,
        connect_timeout: int | timedelta = DEFAULT_CONNECT_TIMEOUT,
        http: HttpConfig | None = None,
    ) -> None:
        super().__init__(
            http=http,
            use_dotenv=use_dotenv,
            log_queries=log_queries,
            datasource=datasource,
            connect_timeout=connect_timeout,
        )
        self._set_generated_properties(
            schema_path=SCHEMA_PATH,
            engine_type=ENGINE_TYPE,
            prisma_models=PRISMA_MODELS,
            packaged_schema_path=PACKAGED_SCHEMA_PATH,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
            preview_features=set([]),
            active_provider='postgresql',
            default_datasource_name='db',
        )

        self.users = actions.usersActions[models.users](self, models.users)
        self.care_settings = actions.care_settingsActions[models.care_settings](self, models.care_settings)
        self.care_logs = actions.care_logsActions[models.care_logs](self, models.care_logs)
        self.reflection_notes = actions.reflection_notesActions[models.reflection_notes](self, models.reflection_notes)
        self.message_logs = actions.message_logsActions[models.message_logs](self, models.message_logs)
        self.walk_missions = actions.walk_missionsActions[models.walk_missions](self, models.walk_missions)
        self.payment = actions.paymentActions[models.payment](self, models.payment)
        self.webhook_events = actions.webhook_eventsActions[models.webhook_events](self, models.webhook_events)

        if auto_register:
            register(self)

    @property
    @override
    def _default_datasource(self) -> Datasource:
        return {
            'name': 'db',
            'url': OptionalValueFromEnvVar(**{'value': None, 'fromEnvVar': 'DATABASE_URL'}).resolve(),
            'source_file_path': 'C:/Dev/Section9_TeamC/backend/prisma/schema.prisma',
        }

    async def execute_raw(self, query: LiteralString, *args: Any) -> int:
        resp = await self._execute(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=None,
        )
        return int(resp['data']['result'])

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> dict[str, Any]:
        ...

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> Optional[BaseModelT]:
        ...

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[Optional[BaseModelT], dict[str, Any]]:
        """This function is the exact same as `query_raw()` but returns the first result.

        If model is given, the returned record is converted to the pydantic model first,
        otherwise a raw dictionary will be returned.
        """
        results: Sequence[Union[BaseModelT, dict[str, Any]]]
        if model is not None:
            results = await self.query_raw(query, *args, model=model)
        else:
            results = await self.query_raw(query, *args)

        if not results:
            return None

        return results[0]

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[dict[str, Any]]:
        ...

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> List[BaseModelT]:
        ...

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[List[BaseModelT], List[dict[str, Any]]]:
        """Execute a raw SQL query against the database.

        If model is given, each returned record is converted to the pydantic model first,
        otherwise results will be raw dictionaries.
        """
        resp = await self._execute(
            method='query_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=model,
        )
        result = resp['data']['result']
        if model is not None:
            return deserialize_raw_results(result, model=model)

        return deserialize_raw_results(result)

    def batch_(self) -> Batch:
        """Returns a context manager for grouping write queries into a single transaction."""
        return Batch(client=self)

    def tx(
        self,
        *,
        max_wait: Union[int, timedelta] = DEFAULT_TX_MAX_WAIT,
        timeout: Union[int, timedelta] = DEFAULT_TX_TIMEOUT,
    ) -> TransactionManager:
        """Returns a context manager for executing queries within a database transaction.

        Entering the context manager returns a new Prisma instance wrapping all
        actions within a transaction, queries will be isolated to the Prisma instance and
        will not be commited to the database until the context manager exits.

        By default, Prisma will wait a maximum of 2 seconds to acquire a transaction from the database. You can modify this
        default with the `max_wait` argument which accepts a value in milliseconds or `datetime.timedelta`.

        By default, Prisma will cancel and rollback ay transactions that last longer than 5 seconds. You can modify this timeout
        with the `timeout` argument which accepts a value in milliseconds or `datetime.timedelta`.

        Example usage:

        ```py
        async with client.tx() as transaction:
            user1 = await client.user.create({'name': 'Robert'})
            user2 = await client.user.create({'name': 'Tegan'})
        ```

        In the above example, if the first database call succeeds but the second does not then neither of the records will be created.
        """
        return TransactionManager(
            client=self,
            max_wait=max_wait,
            timeout=timeout,
        )


TransactionManager = AsyncTransactionManager[Prisma]


# TODO: this should return the results as well
# TODO: don't require copy-pasting arguments between actions and batch actions
class Batch:
    users: 'usersBatchActions'
    care_settings: 'care_settingsBatchActions'
    care_logs: 'care_logsBatchActions'
    reflection_notes: 'reflection_notesBatchActions'
    message_logs: 'message_logsBatchActions'
    walk_missions: 'walk_missionsBatchActions'
    payment: 'paymentBatchActions'
    webhook_events: 'webhook_eventsBatchActions'

    def __init__(self, client: Prisma) -> None:
        self.__client = client
        self.__queries: List[str] = []
        self._active_provider = client._active_provider
        self.users = usersBatchActions(self)
        self.care_settings = care_settingsBatchActions(self)
        self.care_logs = care_logsBatchActions(self)
        self.reflection_notes = reflection_notesBatchActions(self)
        self.message_logs = message_logsBatchActions(self)
        self.walk_missions = walk_missionsBatchActions(self)
        self.payment = paymentBatchActions(self)
        self.webhook_events = webhook_eventsBatchActions(self)

    def _add(self, **kwargs: Any) -> None:
        builder = QueryBuilder(
            **kwargs,
            prisma_models=PRISMA_MODELS,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
        )
        self.__queries.append(builder.build_query())

    async def commit(self) -> None:
        """Execute the queries"""
        # TODO: normalise this, we should still call client._execute
        queries = self.__queries
        self.__queries = []

        payload = {
            'batch': [
                {
                    'query': query,
                    'variables': {},
                }
                for query in queries
            ],
            'transaction': True,
        }
        await self.__client._engine.query(
            dumps(payload),
            tx_id=self.__client._tx_id,
        )

    def execute_raw(self, query: LiteralString, *args: Any) -> None:
        self._add(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            }
        )

    async def __aenter__(self) -> 'Batch':
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        if exc is None:
            await self.commit()


# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class usersBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.usersCreateInput,
        include: Optional[types.usersInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.users,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.usersCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.users,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.usersWhereUniqueInput,
        include: Optional[types.usersInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.users,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.usersUpdateInput,
        where: types.usersWhereUniqueInput,
        include: Optional[types.usersInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.users,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.usersWhereUniqueInput,
        data: types.usersUpsertInput,
        include: Optional[types.usersInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.users,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.usersUpdateManyMutationInput,
        where: types.usersWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.users,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.usersWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.users,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class care_settingsBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.care_settingsCreateInput,
        include: Optional[types.care_settingsInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.care_settings,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.care_settingsCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.care_settings,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.care_settingsWhereUniqueInput,
        include: Optional[types.care_settingsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.care_settings,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.care_settingsUpdateInput,
        where: types.care_settingsWhereUniqueInput,
        include: Optional[types.care_settingsInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.care_settings,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.care_settingsWhereUniqueInput,
        data: types.care_settingsUpsertInput,
        include: Optional[types.care_settingsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.care_settings,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.care_settingsUpdateManyMutationInput,
        where: types.care_settingsWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.care_settings,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.care_settingsWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.care_settings,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class care_logsBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.care_logsCreateInput,
        include: Optional[types.care_logsInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.care_logs,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.care_logsCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.care_logs,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.care_logsWhereUniqueInput,
        include: Optional[types.care_logsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.care_logs,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.care_logsUpdateInput,
        where: types.care_logsWhereUniqueInput,
        include: Optional[types.care_logsInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.care_logs,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.care_logsWhereUniqueInput,
        data: types.care_logsUpsertInput,
        include: Optional[types.care_logsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.care_logs,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.care_logsUpdateManyMutationInput,
        where: types.care_logsWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.care_logs,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.care_logsWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.care_logs,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class reflection_notesBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.reflection_notesCreateInput,
        include: Optional[types.reflection_notesInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.reflection_notes,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.reflection_notesCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.reflection_notes,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.reflection_notesWhereUniqueInput,
        include: Optional[types.reflection_notesInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.reflection_notes,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.reflection_notesUpdateInput,
        where: types.reflection_notesWhereUniqueInput,
        include: Optional[types.reflection_notesInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.reflection_notes,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.reflection_notesWhereUniqueInput,
        data: types.reflection_notesUpsertInput,
        include: Optional[types.reflection_notesInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.reflection_notes,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.reflection_notesUpdateManyMutationInput,
        where: types.reflection_notesWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.reflection_notes,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.reflection_notesWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.reflection_notes,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class message_logsBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.message_logsCreateInput,
        include: Optional[types.message_logsInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.message_logs,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.message_logsCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.message_logs,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.message_logsWhereUniqueInput,
        include: Optional[types.message_logsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.message_logs,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.message_logsUpdateInput,
        where: types.message_logsWhereUniqueInput,
        include: Optional[types.message_logsInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.message_logs,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.message_logsWhereUniqueInput,
        data: types.message_logsUpsertInput,
        include: Optional[types.message_logsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.message_logs,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.message_logsUpdateManyMutationInput,
        where: types.message_logsWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.message_logs,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.message_logsWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.message_logs,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class walk_missionsBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.walk_missionsCreateInput,
        include: Optional[types.walk_missionsInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.walk_missions,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.walk_missionsCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.walk_missions,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.walk_missionsWhereUniqueInput,
        include: Optional[types.walk_missionsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.walk_missions,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.walk_missionsUpdateInput,
        where: types.walk_missionsWhereUniqueInput,
        include: Optional[types.walk_missionsInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.walk_missions,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.walk_missionsWhereUniqueInput,
        data: types.walk_missionsUpsertInput,
        include: Optional[types.walk_missionsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.walk_missions,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.walk_missionsUpdateManyMutationInput,
        where: types.walk_missionsWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.walk_missions,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.walk_missionsWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.walk_missions,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class paymentBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.paymentCreateInput,
        include: Optional[types.paymentInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.payment,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.paymentCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.payment,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.paymentWhereUniqueInput,
        include: Optional[types.paymentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.payment,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.paymentUpdateInput,
        where: types.paymentWhereUniqueInput,
        include: Optional[types.paymentInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.payment,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.paymentWhereUniqueInput,
        data: types.paymentUpsertInput,
        include: Optional[types.paymentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.payment,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.paymentUpdateManyMutationInput,
        where: types.paymentWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.payment,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.paymentWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.payment,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class webhook_eventsBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.webhook_eventsCreateInput,
        include: Optional[types.webhook_eventsInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.webhook_events,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.webhook_eventsCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.webhook_events,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.webhook_eventsWhereUniqueInput,
        include: Optional[types.webhook_eventsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.webhook_events,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.webhook_eventsUpdateInput,
        where: types.webhook_eventsWhereUniqueInput,
        include: Optional[types.webhook_eventsInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.webhook_events,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.webhook_eventsWhereUniqueInput,
        data: types.webhook_eventsUpsertInput,
        include: Optional[types.webhook_eventsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.webhook_events,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.webhook_eventsUpdateManyMutationInput,
        where: types.webhook_eventsWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.webhook_events,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.webhook_eventsWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.webhook_events,
            arguments={'where': where},
            root_selection=['count'],
        )



Client = Prisma