from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'users',
    'care_settings',
    'care_logs',
    'reflection_notes',
    'message_logs',
    'walk_missions',
    'payment',
    'webhook_events',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'users': {
        'care_settings': 'care_settings',
        'message_logs': 'message_logs',
        'payment': 'payment',
    },
    'care_settings': {
        'care_logs': 'care_logs',
        'user': 'users',
        'reflection_notes': 'reflection_notes',
    },
    'care_logs': {
        'care_setting': 'care_settings',
        'walk_missions': 'walk_missions',
    },
    'reflection_notes': {
        'care_setting': 'care_settings',
    },
    'message_logs': {
        'user': 'users',
    },
    'walk_missions': {
        'care_log': 'care_logs',
    },
    'payment': {
        'user': 'users',
    },
    'webhook_events': {
    },
}

# fmt: on